= IntelaJ
:numbered:
Intelaj is a intregated Development enviroment


== Short Cut Keys
This is a list of short cuts for IntelaJ


=== Format clode
Ctrl Alt L

=== shift line down
Shift Alt Down


=== duplicate line down
Ctrl D

=== Add a new line
Shift Enter


=== delete the current line
Ctrl Y

== Window stuff

=== Go to project Window
Alt 1

== Add Vid to Ascii Doc



== straight too the vid

For videos to display in thw browser 
you will need to have the format in mp3.
 

----
link:vid/05_templates.mp4[]
----

----

++++
<iframe width="1366" height="768" src="/home/john/aaa/aaa1_doc/java/ide/intelaj/vid/switch_to_fullscreen_mode.mp4" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
++++


----

== View Mode 
=== Presintation mode

Ctrl Shift A  ==> View m

Ctrl ` 4   1

1366×768

To enter presintation mode. We chose the view option in the top menu.

We then chose the Aperance option which is the second option down. 

And from there we choise "Enter Presintation Mode"

We are now in presintation mode 

To go back we move the mouse cursor to the top of the screen

The menu bar then appers and we can chose View Apperance and exit presintation mode 



++++
<iframe width="1366" height="768" src="/home/john/aaa/aaa1_doc/java/ide/intelaj/vid/switch_to_fullscreen_mode.mp4" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
++++
