all: run

run: makefile.adoc netbeans_FX.adoc
        clear
        asciidoc makefile.adoc
        asciidoc netbeans_FX.adoc
        asciidoc netbeans_FX.adoc
        ls -1
clean:
        clear
        rm *.html
        ls -1

