= This is a Maven Document
// :doctype: book
// :reproducible:
:numbered:
//:source-highlighter: coderay
// :source-highlighter: rouge
// :listing-caption: Listing
// Uncomment next line to set page size (default is A4)
//:pdf-page-size: Letter


== Maven coordinates
// Maven coordinates identify uniquely a project, a dependency, or a plugin defined in POM
A Maven cordinate is that part of a pom file that uniquely identifies that pom file.
// Each entity is uniquely identified by the combination of a group identifier, an artifact identifier, and the version

So the coordinant consists of a combination of 3 parts. 
Those are the 

* group identifier
* the artifact identifier
* and the version

Here is the code from the pom file


<modelVersion>4.0.0</modelVersion> +
<groupId>**[red]#john.org#**</groupId> +
<artifactId>**[red]#tmp#**</artifactId> +
<packaging>jar</packaging> +
<version>*[red]#1.0-SNAPSHOT#**</version> +
<name>tmp</name> +
<url>http://maven.apache.org</url> +

this ia

mvn archetype:generate \ +
-DgroupID=**[red]#john.org#** \ +
-DartifactID=**[red]#tmp#** \ +
-DarchetypeArtifactId=[red]#maven-archetype-quickstart# \ +








=== What is a maven artiface

An **artifact is the jar file** that gets sent to a maven repository 


When you build a Maven project 
you produce an artifact. 

An artifact will have a **jar** file in it. 
It may also have a ** source jar** filein .

Each artifact has a 

* group ID
* artifactId
* version>1.0


// Each artifact has a group ID (usually a reversed domain name, like com.example.foo), an artifact ID (just a name), and a version string. The three together uniquely identify the artifact.

A project's dependencies are specified as artifacts.








== Create a Maven Project


//
//=== set up directory
//
//
//
//=== Set up a basic Project


=== Generate via maven
Here we will create a maven project
we do this by using an archetype

All that you need to do is to copy this code
and then paste it to the linux terminal

[source,bash]
----

mvn archetype:generate \
-DgroupId=john.org \
-DartifactId=tmp \
-DarchetypeArtifactId=maven-archetype-quickstart \
-DarchetypeVersion=1.4 \
-DinteractiveMode=false



----




=== compile and run code

[source,bash]
----
(cd tmp/ && mvn clean)

(cd tmp/ && mvn compile)

tree tmp/

(cd tmp/ && mvn package )

java -cp tmp/target/tmp-1.0-SNAPSHOT.jar john.org.App

----











=== View what has been done 
[source,bash]
----
tree
.
└── aaa_quickstart
    ├── pom.xml
    └── src
        ├── main
        │   └── java
        │       └── john
        │           └── org
        │               └── App.java
        └── test
            └── java
                └── john
                    └── org
                        └── AppTest.java

10 directories, 3 files
----


=== Clean 
The best pracktise
is to  clean everything
before we start. 

we use the [red]#(cd tmp && mvn clean)#
instead of the more simple mvn clean command
becouse we are exicuting maven from outside the tmp directory.




[source,bash]
----
(cd tmp/my-app && mvn clean)
tree tmp
.
├── pom.xml 
└── src
    ├── main
    │   └── java
    │       └── john
    │           └── org
    │               └── App.java
    └── test
        └── java
            └── john
                └── org
                    └── AppTest.java

9 directories, 3 files
[john@localhost tmp]$ 
----



=== Create a Package
Here we will creat a package. 
The Package will be in the target directory.
An as we can see here from the tree listing it is at the bottom of the directory.
The name of the package is the same
as the name of the top level directory

[source,bash]
----
(cd tmp && mvn package)

tree target/
target/
├── classes
│   └── john
│       └── org
│           └── App.class
├── generated-sources
│   └── annotations
├── generated-test-sources
│   └── test-annotations
├── maven-archiver
│   └── pom.properties
├── maven-status
│   └── maven-compiler-plugin
│       ├── compile
│       │   └── default-compile
│       │       ├── createdFiles.lst
│       │       └── inputFiles.lst
│       └── testCompile
│           └── default-testCompile
│               ├── createdFiles.lst
│               └── inputFiles.lst
├── surefire-reports
│   ├── john.org.AppTest.txt
│   └── TEST-john.org.AppTest.xml
├── test-classes
│   └── john
│       └── org
│           └── AppTest.class
└── tmp-1.0-SNAPSHOT.jar

18 directories, 10 files
----



=== Run the Package
Here we will run the package 
that we have just created.

[source,bash]
[john@localhost tmp]$ java -cp target/tmp-1.0-SNAPSHOT.jar john.org.App 
Hello World!
[john@localhost tmp]$ 






